name: ci
on: push
jobs:
  copiar_fichero:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Copiar el archivo existente a uno nuevo
        run: |
          ARCHIVO_ORIGINAL="config.txt"
          ARCHIVO_NUEVO="test_config.txt"       
          echo "Verificando si existe el archivo original..."
          if [ -f $ARCHIVO_ORIGINAL ]; then
            cp $ARCHIVO_ORIGINAL $ARCHIVO_NUEVO
            echo "Contenido del nuevo archivo:"
            cat $ARCHIVO_NUEVO
          else
            echo "ERROR: El archivo $ARCHIVO_ORIGINAL no existe en el repositorio."
            exit 1 # Termina el job con fallo
          fi
